-- ============================================================================
--  sql/005_renumber_limit.sql · tope por corrida + reordenador de id
--  (idempotente: se puede ejecutar tantas veces como quieras)
--
--  NOTA DEL TOPE: p_limit / p_max_deletes ya viven dentro de cada función
--  de purga y de keep_best (003/004): este archivo no necesita redefinirlas.
--
--  torrents_id_report ... total, min/max, huecos, listo, FKs hacia torrents
--  renumber_torrent_ids . deja id en 1..N sin huecos (dos fases, conserva
--                         updated_at y sincroniza la secuencia identity)
-- ============================================================================

create or replace function public.torrents_id_report()
returns table(total bigint, min_id bigint, max_id bigint, huecos bigint,
              listo boolean, siguiente_id bigint, fks bigint)
language sql stable as $fn$
  select count(*),
         min(id), max(id),
         case when count(*) = 0 then 0
              else (max(id) - min(id) + 1) - count(*) end,
         (count(*) = 0 or ((max(id) - min(id) + 1) = count(*) and min(id) = 1)),
         coalesce(max(id), 0) + 1,
         (select count(*) from pg_constraint
           where confrelid = 'public.torrents'::regclass and contype = 'f')
    from public.torrents;
$fn$;

create or replace function public.renumber_torrent_ids(
  p_dry_run boolean default true, p_max_rows integer default 200000,
  p_force boolean default false, p_start integer default 1)
returns table(updated integer, total integer, huecos integer,
              min_id bigint, max_id bigint, min_nuevo bigint, max_nuevo bigint,
              listo boolean, saltado boolean, secuencia text,
              updated_at_conservado boolean, nota text)
language plpgsql as $fn$
declare
  v_total  integer; v_min bigint; v_max bigint; v_huecos integer;
  v_start  integer := greatest(coalesce(p_start, 1), 0);
  v_fks    integer; v_seq text; v_k bigint;
  v_trig   boolean := false;
  v_ya_ok  boolean;
  v_ident  char;
begin
  -- Candado anti-carreras (un INSERT a medio asignar): 15 s y fuera.
  perform set_config('lock_timeout', '15s', true);
  lock table public.torrents in access exclusive mode;

  select count(*), min(t.id), max(t.id) into v_total, v_min, v_max
    from public.torrents t;
  select count(*) into v_fks from pg_constraint
   where confrelid = 'public.torrents'::regclass and contype = 'f';
  v_seq := pg_get_serial_sequence('public.torrents', 'id');

  if v_total = 0 then
    return query select 0, 0, 0, null::bigint, null::bigint,
      null::bigint, null::bigint, true, false, v_seq, true,
      'tabla vacía: nada que reordenar'::text;
    return;
  end if;

  v_huecos := (v_max - v_min + 1) - v_total;

  if v_total > coalesce(p_max_rows, 200000) then
    return query select 0, v_total, v_huecos, v_min, v_max,
      null::bigint, null::bigint, false, true, v_seq, true,
      format('saltado: %s filas superan p_max_rows=%s',
             v_total, p_max_rows)::text;
    return;
  end if;

  if v_fks > 0 and not coalesce(p_force, false) then
    return query select 0, v_total, v_huecos, v_min, v_max,
      null::bigint, null::bigint, false, true, v_seq, true,
      format('saltado: %s clave(s) foránea(s) apuntan a torrents(id); usa p_force=true para forzarlo',
             v_fks)::text;
    return;
  end if;

  select not exists (
    select 1 from (select t.id, row_number() over (order by t.id) + v_start - 1 as deb
                     from public.torrents t) s
     where s.id <> s.deb) into v_ya_ok;
  if v_ya_ok then
    return query select 0, v_total, 0, v_min, v_max, v_min, v_max,
      true, false, v_seq, true,
      format('ya estaba en orden (%s..%s)', v_start, v_start + v_total - 1)::text;
    return;
  end if;

  if coalesce(p_dry_run, true) then
    return query select 0, v_total, v_huecos, v_min, v_max,
      v_start::bigint, (v_start + v_total - 1)::bigint, false, false, v_seq, true,
      format('se pasaría de %s..%s a %s..%s (%s huecos)',
             v_min, v_max, v_start, v_start + v_total - 1, v_huecos)::text;
    return;
  end if;

  -- Apaga el trigger de updated_at (se restaura al final sí o sí).
  if exists (select 1 from pg_trigger
              where tgrelid = 'public.torrents'::regclass
                and tgname = 'update_torrents_updated_at'
                and not tgisinternal) then
    execute 'alter table public.torrents disable trigger update_torrents_updated_at';
    v_trig := true;
  end if;

  -- GENERATED ALWAYS no deja reescribir id: se baja a BY DEFAULT durante
  -- el trabajo (conserva la secuencia) y se devuelve a ALWAYS al final.
  select attidentity into v_ident from pg_attribute
   where attrelid = 'public.torrents'::regclass and attname = 'id';
  if v_ident = 'a' then
    execute 'alter table public.torrents alter column id set generated by default';
  end if;

  -- Mapa viejo -> nuevo (+updated_at para restaurarlo después).
  drop table if exists _rn;
  create temp table _rn on commit drop as
  select t.id as viejo,
         row_number() over (order by t.id) + v_start - 1 as nuevo,
         t.updated_at as upd
    from public.torrents t order by t.id;

  -- Fase 1: todos a un rango altísimo (la PK no es diferible: mover 5->3
  -- chocaría con la fila 3 todavía viva; sumar una constante no choca).
  v_k := greatest(v_max, v_start + v_total) + 1000000;
  update public.torrents set id = id + v_k;

  -- Fase 2: al rango final 1..N (conserva el orden original).
  update public.torrents t set id = m.nuevo
    from _rn m where t.id = m.viejo + v_k;

  -- Fase 3: restaura updated_at (no marcar todo como "recién actualizado").
  update public.torrents t set updated_at = m.upd
    from _rn m where t.id = m.nuevo;

  if v_trig then
    execute 'alter table public.torrents enable trigger update_torrents_updated_at';
  end if;
  if v_ident = 'a' then
    execute 'alter table public.torrents alter column id set generated always';
  end if;

  -- Sincroniza la secuencia identity (si no, el siguiente INSERT choca).
  if v_seq is not null then
    perform setval(v_seq, v_start + v_total - 1, true);
  end if;

  return query select v_total, v_total, v_huecos, v_min, v_max,
    v_start::bigint, (v_start + v_total - 1)::bigint, true, false, v_seq, true,
    format('renumerado de %s..%s a %s..%s',
           v_min, v_max, v_start, v_start + v_total - 1)::text;
end
$fn$;
